export const PLAYER_COLORS = [
  "#FF3B30", // Red
  "#007AFF", // Blue
  "#34C759", // Green
  "#FFCC00", // Yellow
  "#AF52DE", // Purple
  "#FF9500", // Orange
  "#5856D6", // Indigo
  "#FF2D55", // Pink
];

export const PLAYER_CHARACTERS = [
  "🚗"
];

export const EGYPTIAN_NAMES = [
  "Kareem", "Nour", "Omar", "Layla", "Amr", "Dina", "Mostafa", "Rania", "Khaled", "Sara",
  "Hossam", "Mona", "Youssef", "Nada", "Ahmed", "Mariam", "Bassem", "Yasmine", "Tarek", "Eman",
  "Mahmoud", "Hana", "Sherif", "Salma", "Wael", "Nadia", "Hazem", "Aya", "Ashraf", "Doaa",
  "Fares", "Rana", "Tamer", "Heba", "Alaa", "Reem", "Karim", "Nesma", "Walid", "Ghada",
  "Adel", "Shimaa", "Essam", "Asmaa", "Gamal", "Radwa", "Hosni", "Sahar", "Magdy", "Engy",
  "Gaml", "Yassin", "Mohamed"
];

export const BOARD_DATA = [
  { id: 0, name: "بداية", type: "START", color: "transparent" },
  { id: 1, name: "القصبجي", type: "PROPERTY", group: "elmoneeb", price: 40, rent: [2, 10, 30, 90, 160, 250], buildCost: 50 },
  { id: 2, name: "كنز", type: "TREASURE" },
  { id: 3, name: "ميدان المنيب", type: "PROPERTY", group: "elmoneeb", price: 50, rent: [4, 20, 60, 180, 320, 450], buildCost: 50 },
  { id: 4, name: "ضريبة دخل 15%", type: "TAX", value: 15 },
  { id: 5, name: "كورنيش العجوزة", type: "PROPERTY", group: "dokki_agouza", price: 60, rent: [4, 20, 60, 180, 320, 450], buildCost: 50 },
  { id: 6, name: "OES", type: "AIRPORT", price: 200, rent: [25, 50, 100, 200] },
  { id: 7, name: "نادي الصيد", type: "PROPERTY", group: "dokki_agouza", price: 65, rent: [4, 20, 60, 180, 320, 450], buildCost: 50 },
  { id: 8, name: "شارع الدقي", type: "PROPERTY", group: "dokki_agouza", price: 70, rent: [4, 20, 60, 180, 320, 450], buildCost: 50 },
  { id: 9, name: "مفاجأة", type: "SURPRISE" },
  { id: 10, name: "شارع إمبابة", type: "PROPERTY", group: "boulaq_dakrour", price: 80, rent: [6, 30, 90, 270, 400, 550], buildCost: 50 },
  { id: 11, name: "الوراق", type: "PROPERTY", group: "boulaq_dakrour", price: 85, rent: [6, 30, 90, 270, 400, 550], buildCost: 50 },
  { id: 12, name: "سجن", type: "PRISON" },
  { id: 13, name: "بولاق الدكرور", type: "PROPERTY", group: "boulaq_dakrour", price: 90, rent: [6, 30, 90, 270, 400, 550], buildCost: 50 },
  { id: 14, name: "ميدان السفينكس", type: "PROPERTY", group: "mohandeseen", price: 100, rent: [6, 30, 90, 270, 400, 550], buildCost: 50 },
  { id: 15, name: "شركة الكهرباء", type: "COMPANY", price: 150 },
  { id: 16, name: "ميدان لبنان", type: "PROPERTY", group: "mohandeseen", price: 100, rent: [6, 30, 90, 270, 400, 550], buildCost: 50 },
  { id: 17, name: "جامعة الدول", type: "PROPERTY", group: "mohandeseen", price: 110, rent: [6, 30, 90, 270, 400, 550], buildCost: 50 },
  { id: 18, name: "LRDL", type: "AIRPORT", price: 200, rent: [25, 50, 100, 200] },
  { id: 19, name: "أبو الهول", type: "PROPERTY", group: "haram", price: 120, rent: [8, 40, 100, 300, 450, 600], buildCost: 100 },
  { id: 20, name: "كنز", type: "TREASURE" },
  { id: 21, name: "نزلة السمان", type: "PROPERTY", group: "haram", price: 120, rent: [8, 40, 100, 300, 450, 600], buildCost: 100 },
  { id: 22, name: "شارع الهرم", type: "PROPERTY", group: "haram", price: 130, rent: [8, 40, 100, 300, 450, 600], buildCost: 100 },
  { id: 23, name: "الطالبية", type: "PROPERTY", group: "faisal", price: 140, rent: [8, 40, 100, 300, 450, 600], buildCost: 100 },
  { id: 24, name: "إجازة", type: "VACATION" },
  { id: 25, name: "العريش", type: "PROPERTY", group: "faisal", price: 160, rent: [14, 70, 200, 550, 750, 950], buildCost: 100 },
  { id: 26, name: "مفاجأة", type: "SURPRISE" },
  { id: 27, name: "الششيني", type: "PROPERTY", group: "faisal", price: 180, rent: [14, 70, 200, 550, 750, 950], buildCost: 100 },
  { id: 28, name: "كنز", type: "TREASURE" },
  { id: 29, name: "العشرين", type: "PROPERTY", group: "faisal", price: 200, rent: [14, 70, 200, 550, 750, 950], buildCost: 150 },
  { id: 30, name: "NIS", type: "AIRPORT", price: 200, rent: [25, 50, 100, 200] },
  { id: 31, name: "الحصري", type: "PROPERTY", group: "sixth_october", price: 220, rent: [18, 90, 250, 700, 875, 1050], buildCost: 150 },
  { id: 32, name: "الحي الأول", type: "PROPERTY", group: "sixth_october", price: 240, rent: [18, 90, 250, 700, 875, 1050], buildCost: 150 },
  { id: 33, name: "شركة المياه", type: "COMPANY", price: 150 },
  { id: 34, name: "المتميز", type: "PROPERTY", group: "sixth_october", price: 260, rent: [18, 90, 250, 700, 875, 1050], buildCost: 150 },
  { id: 35, name: "نيوم", type: "PROPERTY", group: "northern_expansions", price: 280, rent: [26, 130, 390, 900, 1100, 1300], buildCost: 200 },
  { id: 36, name: "ادخل السجن", type: "GO_TO_JAIL" },
  { id: 37, name: "ماونتن فيو", type: "PROPERTY", group: "northern_expansions", price: 285, rent: [26, 130, 390, 900, 1100, 1300], buildCost: 200 },
  { id: 38, name: "ضريبة فاخرة 100$", type: "TAX", value: 100 },
  { id: 39, name: "جراند هايتس", type: "PROPERTY", group: "northern_expansions", price: 290, rent: [26, 130, 390, 900, 1100, 1300], buildCost: 200 },
  { id: 40, name: "مفاجأة", type: "SURPRISE" },
  { id: 41, name: "بالم هيلز", type: "PROPERTY", group: "sheikh_zayed", price: 300, rent: [26, 130, 390, 900, 1100, 1300], buildCost: 200 },
  { id: 42, name: "NVIS", type: "AIRPORT", price: 200, rent: [25, 50, 100, 200] },
  { id: 43, name: "بيفرلي هيلز", type: "PROPERTY", group: "sheikh_zayed", price: 320, rent: [26, 130, 390, 900, 1100, 1300], buildCost: 200 },
  { id: 44, name: "شارع الأهرام", type: "PROPERTY", group: "zamalek_giza", price: 380, rent: [35, 175, 500, 1100, 1300, 1500], buildCost: 200 },
  { id: 45, name: "كنز", type: "TREASURE" },
  { id: 46, name: "جزيرة الزمالك", type: "PROPERTY", group: "zamalek_giza", price: 400, rent: [40, 200, 600, 1400, 1700, 2000], buildCost: 250 },
  { id: 47, name: "برج القاهرة", type: "PROPERTY", group: "zamalek_giza", price: 400, rent: [40, 200, 600, 1400, 1700, 2000], buildCost: 250 },
];

export const COLORS = {
  dokki_agouza: "#8B4513",
  mohandeseen: "#87CEEB",
  haram: "#FF69B4",
  faisal: "#FFA500",
  sixth_october: "#FF0000",
  sheikh_zayed: "#008000",
  zamalek_giza: "#00008B",
  northern_expansions: "#0D9488",
  boulaq_dakrour: "#7C3AED",
  elmoneeb: "#9F1239",
};

export const ENGLISH = {
  battleLog: "Battle Log",
  treasure: "Treasure",
  surprise: "Surprise",
  tax: "Tax",
  owned: "Owned",
  upgrade: "Upgrade",
  sell: "Sell",
  mortgage: "Mortgage",
  getOutOfJail: "Get Out of Jail",
  goToJail: "Go To Jail",
  vacation: "Vacation",
  start: "Start",
  prison: "Prison",
  buy: "Buy",
  trade: "Trade",
  roll: "Roll Dice",
  endTurn: "End Turn",
  startingMoney: "Starting Money",
  turnTimer: "Turn Timer",
  auction: "Auction",
  evenBuild: "Even Build",
  allowTrading: "Allow Trading",
  doubleRent: "Double Rent",
  vacationCash: "Vacation Cash",
  prisonNoRent: "No Rent in Prison",
  randomizePlayerOrder: "Randomize Player Order",
  kick: "Kick",
  startGame: "Start Game",
  waiting: "Waiting for players...",
  host: "Host",
  you: "You",
  bankrupt: "Bankrupt!",
  winner: "Winner!",
  yourName: "Your Name",
  enterName: "Enter your name...",
  roomNumber: "Room Number",
  enterRoom: "Enter room number...",
  yourColor: "Your Color",
  joinGame: "Join Game",
  cancel: "Cancel",
  confirmOffer: "Confirm Offer",
  yourProperties: "Your Properties",
  offeredMoney: "Offered Money",
  theirProperties: "Their Properties",
  requestedMoney: "Requested Money",
  steal: "Steal (Soon)",
  auctionTitle: "Auction!",
  currentBid: "Current Bid",
  bid: "Bid",
  pass: "Pass",
  chatPlaceholder: "Type a message...",
  room: "Room",
  gameStarted: "Game Started!",
  roomSettings: "Room Settings",
  chat: "Chat",
  addBot: "Add Bot",
  privateChat: "Private Chat",
  highestBidder: "Highest Bidder",
  none: "None",
  currentBalance: "Current Balance",
  when: "when",
  get: "get",
  withRent: "with rent",
  withOneHouse: "with one house",
  withTwoHouses: "with two houses",
  withThreeHouses: "with three houses",
  withFourHouses: "with four houses",
  withHotel: "with a hotel",
  price: "Price",
  owner: "Owner",
  shareGame: "Share Game",
  copy: "Copy",
  playerList: "Player List",
  tradeLog: "Trade Log",
  pay_jail: "Pay $50 to leave",
  activeTrades: "Active Trades",
  view: "View",
  noActiveTrades: "No active trades",
  character: "Character",
  selectCharacter: "Select your character",
  history_jail_3_doubles: "{player} rolled 3 doubles and went to jail!",
  history_pass_start: "{player} passed START and collected $200",
  history_land_on: "{player} landed on {tile}",
  history_buy_property: "{player} bought {tile}",
  history_start_auction: "An auction started for {tile}!",
  history_send_trade: "{player} sent a trade offer to {target}",
  history_accept_trade: "{target} accepted the trade offer from {player}",
  history_decline_trade: "{target} declined the trade offer from {player}",
  history_cancel_trade: "{player} canceled their trade offer",
  history_bankrupt: "{player} went bankrupt!",
  history_jail_double: "{player} rolled a double and left jail!",
  history_jail_2_turns: "{player} spent 2 turns in jail, paid $50 and left",
  history_pay_jail: "{player} paid $50 to leave jail early",
  history_still_in_jail: "{player} is still in jail (turn {turns}/2)",
  history_place_bid: "{player} bid ${amount} (Total: ${total})",
  history_win_auction: "{player} won the auction for {tile} for ${amount}!",
  history_no_one_bought: "No one bought the property in the auction.",
  history_upgrade_property: "{player} upgraded {tile} to level {level}",
  history_downgrade_property: "{player} sold an upgrade from {tile}",
  history_mortgage_property: "{player} mortgaged {tile}",
  history_unmortgage_property: "{player} unmortgaged {tile}",
  history_sell_property: "{player} sold {tile}",
  history_game_over: "Game Over! The winner is {winner}",
  history_sell_house_crisis: "{player} sold a house from {tile} due to cash need",
  history_mortgage_property_crisis: "{player} mortgaged {tile} due to cash need",
  history_counter_offer: "{player} declined the offer and made a counter-offer to {target}",
  history_initiate_trade_prop: "{player} offered to trade {myProp} for {targetProp} with {target}",
  history_initiate_trade_money: "{player} offered ${amount} for {targetProp} from {target}",
  history_pay_tax: "{player} paid ${amount} tax",
  history_go_to_jail: "{player} went to jail!",
  history_pay_rent: "{player} paid ${amount} rent to {target}",
  history_test_mode_all_props: "{player} used test mode and took all properties!",
  history_win_vacation_cash: "{player} landed on Vacation and won ${amount} free cash!",
  history_gain_money_card: "{player} drew: {title} (+${amount})",
  history_pay_fine_card: "{player} drew: {title} (-${amount})",
  history_pay_tax_card: "{player} paid property tax: {title} (-${amount})",
};

export const EGYPTIAN_ARABIC = {
  battleLog: "سجل اللعب",
  treasure: "كنز",
  surprise: "مفاجأة",
  tax: "ضريبة",
  owned: "مملوك",
  upgrade: "تطوير",
  sell: "بيع",
  mortgage: "رهن",
  getOutOfJail: "كارت خروج من السجن",
  goToJail: "ادخل السجن",
  vacation: "إجازة",
  start: "بداية",
  prison: "سجن",
  buy: "شراء",
  trade: "مقايضة",
  roll: "ارمي الزهر",
  endTurn: "إنهاء الدور",
  startingMoney: "فلوس البداية",
  turnTimer: "وقت الدور",
  auction: "مزاد",
  evenBuild: "بناء متساوي",
  allowTrading: "سماح بالمقايضة",
  doubleRent: "إيجار مضاعف للمجموعة",
  vacationCash: "كاش الإجازة",
  prisonNoRent: "لا إيجار في السجن",
  randomizePlayerOrder: "ترتيب عشوائي للاعبين",
  kick: "طرد",
  startGame: "ابدأ اللعبة",
  waiting: "مستنيين اللعيبة...",
  host: "المضيف",
  you: "أنت",
  bankrupt: "أفلست!",
  winner: "الفائز!",
  yourName: "اسمك",
  enterName: "أدخل اسمك...",
  roomNumber: "رقم الغرفة",
  enterRoom: "أدخل رقم الغرفة...",
  yourColor: "لونك",
  joinGame: "ادخل اللعبة",
  cancel: "إلغاء",
  confirmOffer: "تأكيد العرض",
  yourProperties: "أملاكك",
  offeredMoney: "الفلوس المعروضة",
  theirProperties: "أملاكه",
  requestedMoney: "الفلوس المطلوبة",
  steal: "سرقة (قريباً)",
  auctionTitle: "مزاد علني!",
  currentBid: "أعلى سعر",
  bid: "زايد",
  pass: "انسحب",
  chatPlaceholder: "اكتب رسالة...",
  room: "غرفة",
  gameStarted: "بدأت اللعبة!",
  roomSettings: "إعدادات الغرفة",
  chat: "الدردشة",
  addBot: "إضافة روبوت",
  privateChat: "دردشة خاصة",
  highestBidder: "أعلى مزايد",
  none: "لا يوجد",
  currentBalance: "رصيدك الحالي",
  when: "الحالة",
  get: "الإيجار",
  withRent: "إيجار عادي",
  withOneHouse: "بيت واحد",
  withTwoHouses: "بيتين",
  withThreeHouses: "3 بيوت",
  withFourHouses: "4 بيوت",
  withHotel: "فندق",
  price: "السعر",
  owner: "المالك",
  shareGame: "مشاركة اللعبة",
  copy: "نسخ",
  playerList: "قائمة اللاعبين",
  tradeLog: "سجل المقايضات",
  pay_jail: "ادفع 50$ للخروج",
  activeTrades: "المقايضات النشطة",
  view: "عرض",
  noActiveTrades: "لا يوجد مقايضات نشطة",
  character: "الشخصية",
  selectCharacter: "اختار شخصيتك",
  history_jail_3_doubles: "{player} جاب 3 دبل وراح السجن!",
  history_pass_start: "{player} مر على البداية وأخد 200$",
  history_land_on: "{player} وصل لـ {tile}",
  history_buy_property: "{player} اشترى {tile}",
  history_start_auction: "بدأ مزاد على {tile}!",
  history_send_trade: "{player} أرسل عرض مقايضة لـ {target}",
  history_accept_trade: "{target} قبل عرض المقايضة من {player}",
  history_decline_trade: "{target} رفض عرض المقايضة من {player}",
  history_cancel_trade: "{player} لغى عرض المقايضة بتاعه",
  history_bankrupt: "{player} أعلن إفلاسه!",
  history_jail_double: "{player} جاب دبل وخرج من السجن!",
  history_jail_2_turns: "{player} كمل دورين في السجن ودفع 50$ وخرج",
  history_pay_jail: "{player} دفع 50$ عشان يخرج من السجن بدري",
  history_still_in_jail: "{player} لسه في السجن (دور {turns}/2)",
  history_place_bid: "{player} زود المزاد بـ {amount}$ (الإجمالي: {total}$)",
  history_win_auction: "{player} كسب المزاد على {tile} بـ {amount}$!",
  history_no_one_bought: "محدش اشترى العقار في المزاد.",
  history_upgrade_property: "{player} طور {tile} للمستوى {level}",
  history_downgrade_property: "{player} باع تطوير من {tile}",
  history_mortgage_property: "{player} رهن {tile}",
  history_unmortgage_property: "{player} فك رهن {tile}",
  history_sell_property: "{player} باع {tile}",
  history_game_over: "اللعبة خلصت! الفائز هو {winner}",
  history_sell_house_crisis: "{player} باع بيت من {tile} عشان محتاج كاش",
  history_mortgage_property_crisis: "{player} رهن {tile} عشان محتاج كاش",
  history_counter_offer: "{player} رفض العرض وقدم عرض مضاد لـ {target}",
  history_initiate_trade_prop: "{player} عرض تبادل {myProp} مقابل {targetProp} مع {target}",
  history_initiate_trade_money: "{player} عرض {amount}$ مقابل {targetProp} من {target}",
  history_pay_tax: "{player} دفع ضريبة {amount}$",
  history_go_to_jail: "{player} دخل السجن!",
  history_pay_rent: "{player} دفع {amount}$ إيجار لـ {target}",
  history_test_mode_all_props: "{player} استخدم وضع الاختبار وأخذ كل الأملاك!",
  history_win_vacation_cash: "{player} نزل على الإجازة وكسب {amount}$ كاش مجاني!",
  history_gain_money_card: "{player} حظه حلو: {title} (+{amount}$)",
  history_pay_fine_card: "{player} دفع غرامة: {title} (-{amount}$)",
  history_pay_tax_card: "{player} دفع ضريبة أملاك: {title} (-{amount}$)",
};

export const ENGLISH_BOARD_DATA = [
  { id: 0, name: "START", type: "START", color: "transparent" },
  { id: 1, name: "Al-Kasabgi", type: "PROPERTY", group: "elmoneeb", price: 40, rent: [2, 10, 30, 90, 160, 250], buildCost: 50 },
  { id: 2, name: "Treasure", type: "TREASURE" },
  { id: 3, name: "El-Moneeb Square", type: "PROPERTY", group: "elmoneeb", price: 50, rent: [4, 20, 60, 180, 320, 450], buildCost: 50 },
  { id: 4, name: "Earnings Tax", type: "TAX", value: 200 },
  { id: 5, name: "Agouza Corniche", type: "PROPERTY", group: "dokki_agouza", price: 60, rent: [4, 20, 60, 180, 320, 450], buildCost: 50 },
  { id: 6, name: "OES", type: "AIRPORT", price: 200, rent: [25, 50, 100, 200] },
  { id: 7, name: "Shooting Club", type: "PROPERTY", group: "dokki_agouza", price: 65, rent: [4, 20, 60, 180, 320, 450], buildCost: 50 },
  { id: 8, name: "Dokki St", type: "PROPERTY", group: "dokki_agouza", price: 70, rent: [4, 20, 60, 180, 320, 450], buildCost: 50 },
  { id: 9, name: "Surprise", type: "SURPRISE" },
  { id: 10, name: "Imbaba St", type: "PROPERTY", group: "boulaq_dakrour", price: 80, rent: [6, 30, 90, 270, 400, 550], buildCost: 50 },
  { id: 11, name: "Al-Warraq", type: "PROPERTY", group: "boulaq_dakrour", price: 85, rent: [6, 30, 90, 270, 400, 550], buildCost: 50 },
  { id: 12, name: "Prison", type: "PRISON" },
  { id: 13, name: "Boulaq El-Dakrour", type: "PROPERTY", group: "boulaq_dakrour", price: 90, rent: [6, 30, 90, 270, 400, 550], buildCost: 50 },
  { id: 14, name: "Sphinx Square", type: "PROPERTY", group: "mohandeseen", price: 100, rent: [6, 30, 90, 270, 400, 550], buildCost: 50 },
  { id: 15, name: "Electric Company", type: "COMPANY", price: 150 },
  { id: 16, name: "Lebanon Square", type: "PROPERTY", group: "mohandeseen", price: 100, rent: [6, 30, 90, 270, 400, 550], buildCost: 50 },
  { id: 17, name: "Gameat El-Dowal", type: "PROPERTY", group: "mohandeseen", price: 110, rent: [6, 30, 90, 270, 400, 550], buildCost: 50 },
  { id: 18, name: "LRDL", type: "AIRPORT", price: 200, rent: [25, 50, 100, 200] },
  { id: 19, name: "Abu El-Hol", type: "PROPERTY", group: "haram", price: 120, rent: [8, 40, 100, 300, 450, 600], buildCost: 100 },
  { id: 20, name: "Treasure", type: "TREASURE" },
  { id: 21, name: "Nazlet El-Semman", type: "PROPERTY", group: "haram", price: 120, rent: [8, 40, 100, 300, 450, 600], buildCost: 100 },
  { id: 22, name: "Al-Haram St", type: "PROPERTY", group: "haram", price: 130, rent: [8, 40, 100, 300, 450, 600], buildCost: 100 },
  { id: 23, name: "Al-Talbya", type: "PROPERTY", group: "faisal", price: 140, rent: [8, 40, 100, 300, 450, 600], buildCost: 100 },
  { id: 24, name: "Vacation", type: "VACATION" },
  { id: 25, name: "Arish", type: "PROPERTY", group: "faisal", price: 160, rent: [14, 70, 200, 550, 750, 950], buildCost: 100 },
  { id: 26, name: "Surprise", type: "SURPRISE" },
  { id: 27, name: "Al-Shesheini", type: "PROPERTY", group: "faisal", price: 180, rent: [14, 70, 200, 550, 750, 950], buildCost: 100 },
  { id: 28, name: "Treasure", type: "TREASURE" },
  { id: 29, name: "Al-Eshrein", type: "PROPERTY", group: "faisal", price: 200, rent: [14, 70, 200, 550, 750, 950], buildCost: 150 },
  { id: 30, name: "NIS", type: "AIRPORT", price: 200, rent: [25, 50, 100, 200] },
  { id: 31, name: "Al-Hosary", type: "PROPERTY", group: "sixth_october", price: 220, rent: [18, 90, 250, 700, 875, 1050], buildCost: 150 },
  { id: 32, name: "1st District", type: "PROPERTY", group: "sixth_october", price: 240, rent: [18, 90, 250, 700, 875, 1050], buildCost: 150 },
  { id: 33, name: "Water Company", type: "COMPANY", price: 150 },
  { id: 34, name: "Al-Motamyez", type: "PROPERTY", group: "sixth_october", price: 260, rent: [18, 90, 250, 700, 875, 1050], buildCost: 150 },
  { id: 35, name: "Neyoum", type: "PROPERTY", group: "northern_expansions", price: 280, rent: [26, 130, 390, 900, 1100, 1300], buildCost: 200 },
  { id: 36, name: "Go To Jail", type: "GO_TO_JAIL" },
  { id: 37, name: "Mountain View", type: "PROPERTY", group: "northern_expansions", price: 285, rent: [26, 130, 390, 900, 1100, 1300], buildCost: 200 },
  { id: 38, name: "Premium Tax", type: "TAX", value: 100 },
  { id: 39, name: "Grand Heights", type: "PROPERTY", group: "northern_expansions", price: 290, rent: [26, 130, 390, 900, 1100, 1300], buildCost: 200 },
  { id: 40, name: "Surprise", type: "SURPRISE" },
  { id: 41, name: "Palm Hills", type: "PROPERTY", group: "sheikh_zayed", price: 300, rent: [26, 130, 390, 900, 1100, 1300], buildCost: 200 },
  { id: 42, name: "NVIS", type: "AIRPORT", price: 200, rent: [25, 50, 100, 200] },
  { id: 43, name: "Beverly Hills", type: "PROPERTY", group: "sheikh_zayed", price: 320, rent: [26, 130, 390, 900, 1100, 1300], buildCost: 200 },
  { id: 44, name: "Pyramids Rd", type: "PROPERTY", group: "zamalek_giza", price: 380, rent: [35, 175, 500, 1100, 1300, 1500], buildCost: 200 },
  { id: 45, name: "Treasure", type: "TREASURE" },
  { id: 46, name: "Zamalek Island", type: "PROPERTY", group: "zamalek_giza", price: 400, rent: [40, 200, 600, 1400, 1700, 2000], buildCost: 250 },
  { id: 47, name: "Cairo Tower", type: "PROPERTY", group: "zamalek_giza", price: 400, rent: [40, 200, 600, 1400, 1700, 2000], buildCost: 250 },
];

